<?php
/**
 * Test class for Mergy_Revision_Builder.
 * Generated by PHPUnit on 2012-03-27 at 08:25:24.
 */
class Mergy_Revision_BuilderTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Mergy_Revision_Builder
     */
    protected $_object;

    /**
     * Test params for the aggregator
     *
     * @var array
     */
    protected $_aParams = array(
        'test',
        '1',
        'testpath',
        'modified'
    );

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->_object = new Mergy_Revision_Builder(Mergy_Revision_Builder::SUBVERSION);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * Test building a revision
     */
    public function testBuild() {
        $oRevision = $this->_object->build('test', 1, $this);
        $this->assertInstanceOf('Mergy_Revision', $oRevision);
        $this->assertEquals('test', $oRevision->sRepository);
        $this->assertEquals(1, $oRevision->iRevision);
    }

    /**
     * @dataProvider getAggregatorProvider
     */
    public function testGetAggregator($sExpected, $sAggregator, $aParams) {
        $oAggregator = $this->_object->getAggregator($sAggregator, $aParams);

        $this->assertInstanceOf($sExpected, $oAggregator);
        $this->assertInstanceOf('Mergy_Revision_AggregatorAbstract', $oAggregator);
    }

    /**
     *
     */
    public function getAggregatorProvider() {
        return array(
            array(
                'Mergy_Revision_Subversion_Info',
                Mergy_Revision_Builder::AGGREGATE_INFO,
                $this->_aParams
            ),
            array(
                'Mergy_Revision_Subversion_Files',
                Mergy_Revision_Builder::AGGREGATE_FILES,
                $this->_aParams
            ),
            array(
                'Mergy_Revision_Subversion_Diff',
                Mergy_Revision_Builder::AGGREGATE_DIFF,
                $this->_aParams
            )

        );
    }
}
