<?php
/**
 * Test class for Mergy_Notifier.
 * Generated by PHPUnit on 2012-03-27 at 08:35:29.
 */
class Mergy_NotifierTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Mergy_Notifier
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $oConfig = json_decode('{"notifiers": {"stdout": {"enabled": true}, "file": {"enabled": false}}}');
        $this->_object = new Mergy_Notifier($oConfig);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testNotify().
     */
    public function testNotify() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @todo Implement testGetNotifiers().
     */
    public function testGetNotifiers() {
        $aNotifiers = $this->_object->getNotifiers();
        $this->assertCount(1, $aNotifiers);

        $oNotifier = reset($aNotifiers);
        $this->assertInstanceOf('Mergy_AbstractNotifier', $oNotifier);
        $this->assertInstanceOf('Mergy_Notifier_Stdout', $oNotifier);
    }
}
