<?php

/**
 * Test class for Mergy_TextUI_Output_Group.
 * Generated by PHPUnit on 2012-03-23 at 23:24:12.
 */
class Mergy_TextUI_Output_GroupTest extends PHPUnit_Framework_TestCase {

    /**
     *
     * @var Mergy_TextUI_Output_Group
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $aRevisions = include 'Tests/_files/Revisions.php';

        $this->_object = new Mergy_TextUI_Output_Group();
        $this->_object->setRevisions($aRevisions);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * Test the output
     */
    public function testGet() {
        $sReturn = $this->_object->get();
        $aLines = explode(PHP_EOL, $sReturn);
        $this->assertEquals(8, count($aLines));
        $this->assertContains('unspecified', $aLines[0]);
        $this->assertEquals(1, count(explode(',', $aLines[1])));
        $this->assertContains('123', $aLines[2]);
        $this->assertEquals(4, count(explode(',', $aLines[3])));
        $this->assertContains('234', $aLines[4]);
        $this->assertEquals(3, count(explode(',', $aLines[5])));
        $this->assertContains('456', $aLines[6]);
        $this->assertEquals(1, count(explode(',', $aLines[7])));
    }
}
