<?php

/**
 * Test class for Mergy_TextUI_Output_Group.
 * Generated by PHPUnit on 2012-03-23 at 23:24:12.
 */
class Mergy_TextUI_Output_ListTest extends PHPUnit_Framework_TestCase {

    /**
     *
     * @var Mergy_TextUI_Output_Group
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $aRevisions = include 'Tests/_files/Revisions.php';

        $this->object = new Mergy_TextUI_Output_List();
        $this->object->setRevisions($aRevisions);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * Test the output
     */
    public function testGet() {
        $sReturn = $this->object->get();
        $aLines = explode(PHP_EOL, $sReturn);
        $this->assertEquals(9, count($aLines));
    }
}
