<?php
/**
 * Test class for Mergy_Util_Parallel_Transport_SharedMemory.
 * Generated by PHPUnit on 2012-03-24 at 14:59:34.
 */
class Mergy_Util_Parallel_Transport_SharedMemoryTest extends Tests_Util_Parallel_Transport_TestAbstract {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->_sTestClass = 'Mergy_Util_Parallel_Transport_SharedMemory';
        parent::setUp();
    }
}
