<?php
/**
 * Test class for \Mergy\Revision\Builder.
 * Generated by PHPUnit on 2012-03-27 at 08:25:24.
 */
namespace Mergy\Test;

class BuilderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var \Mergy\Revision\Builder
     */
    protected $_object;

    /**
     * Test params for the aggregator
     *
     * @var array
     */
    protected $_aParams = array(
        'test',
        '1',
        'testpath',
        'modified'
    );

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->_object = new \Mergy\Revision\Builder(\Mergy\Revision\Builder::SUBVERSION, new \Mergy\Util\Command());
    }

    /**
     * Test building a revision
     */
    public function testBuild() {
        $oRevision = $this->_object->build('test', 1, $this);
        $this->assertInstanceOf('\\Mergy\\Revision', $oRevision);
        $this->assertEquals('test', $oRevision->sRepository);
        $this->assertEquals(1, $oRevision->iRevision);
    }

    /**
     * @dataProvider getAggregatorProvider
     */
    public function testGetAggregator($sExpected, $sAggregator, $aParams) {
        $oAggregator = $this->_object->getAggregator($sAggregator, $aParams);

        $this->assertInstanceOf($sExpected, $oAggregator);
        $this->assertInstanceOf('\\Mergy\\Revision\\AggregatorAbstract', $oAggregator);
    }

    /**
     *
     */
    public function getAggregatorProvider() {
        return array(
            array(
                '\\Mergy\\Revision\\Subversion\\Info',
                \Mergy\Revision\Builder::AGGREGATE_INFO,
                $this->_aParams
            ),
            array(
                '\\Mergy\\Revision\\Subversion\\Files',
                \Mergy\Revision\Builder::AGGREGATE_FILES,
                $this->_aParams
            ),
            array(
                '\\Mergy\\Revision\\Subversion\\Diff',
                \Mergy\Revision\Builder::AGGREGATE_DIFF,
                $this->_aParams
            )

        );
    }
}
