<?php

/**
 * Test class for Mergy_TextUI_Printer_Group.
 * Generated by PHPUnit on 2012-03-23 at 23:24:12.
 */
class Mergy_TextUI_Printer_ListTest extends PHPUnit_Framework_TestCase {

    /**
     *
     * @var Mergy_TextUI_Printer_Group
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $aRevisions = include 'Tests/_files/Revisions.php';

        $this->_object = new Mergy_TextUI_Printer_List();
        $this->assertInstanceOf(get_class($this->_object), $this->_object->setFormatter(new Mergy_TextUI_Printer_Formatter_Text()));
        $this->assertInstanceOf(get_class($this->_object), $this->_object->setRevisions($aRevisions));
    }

    /**
     * Test the output
     */
    public function testGet() {
        $sReturn = $this->_object->get();
        $aLines = explode(PHP_EOL, $sReturn);
        $this->assertEquals(9, count($aLines));
    }
}
