<?php
/**
 * Test class for Mergy_Notifier_File.
 * Generated by PHPUnit on 2011-10-22 at 23:00:50.
 */
class Mergy_Notifier_FileTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Mergy_Notifier_File
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $oConfig = new stdClass();
        $oConfig->path = '/tmp';

        $this->_object = new Mergy_Notifier_File($oConfig);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() {
        unlink('/tmp/mergy.log');
    }

    /**
     * Test simple notify call
     */
    public function testNotify() {
        $this->assertInstanceOf('Mergy_AbstractNotifier', $this->_object->notify(Mergy_AbstractNotifier::SUCCESS, ''));
    }
}
