<?php
/**
 * Test class for Mergy_Notifier_Stdout.
 * Generated by PHPUnit on 2011-10-22 at 23:00:50.
 */
class Mergy_Notifier_StdoutTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Mergy_Notifier_Stdout
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->_object = new Mergy_Notifier_Stdout();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * Test simple add call
     */
    public function testNotify() {
        $this->expectOutputRegex('/Test/');
        $this->assertInstanceOf('Mergy_AbstractNotifier', $this->_object->notify(Mergy_AbstractNotifier::SUCCESS, 'Test'));
    }
}
