<?php
/**
 * Test class for Mergy_Action_Merge_Decision_Ticket.
 * Generated by PHPUnit on 2012-03-25 at 19:45:01.
 */
namespace Mergy\Test\Mergy\Action\Merge\Decision;

class TicketTest extends \PHPUnit_Framework_TestCase {

    /**
     * Test ticket parsing
     *
     * @dataProvider parseTicketProvider
     */
    public function testParseTicket($sInfo, $sExpected) {
        $this->assertEquals($sExpected, \Mergy\Action\Merge\Decision\Ticket::parseTicket($sInfo));
    }

    /**
     * Dataprovider for testParseTicket
     *
     * @return multitype:multitype:string number  multitype:string boolean
     */
    public function parseTicketProvider() {
        return array(
            array(
                'bug=123',
                123
            ),
            array(
                'http://bugzilla/?bug_id=123',
                123
            ),
            array(
                'bug 123 http://bugzilla/?bug_id=123',
                123
            ),
            array(
                'https://github.com/issues/28',
                28
            ),
            array(
                'http://trac/ticket/4431',
                4431
            ),
            array(
                'works now',
                false
            ),
            array(
                'text with a 12434 number',
                false
            ),
        );
    }
}
