<?php

/**
 * Test class for \Mergy\TextUI\Printer\Group.
 * Generated by PHPUnit on 2012-03-23 at 23:24:12.
 */
namespace Mergy\Test\Mergy\TextUI\Printer;

class GroupTest extends \PHPUnit_Framework_TestCase {

    /**
     *
     * @var \Mergy\TextUI\Printer\Group
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $aRevisions = include 'tests/_files/Revisions.php';

        $this->_object = new \Mergy\TextUI\Printer\Group();
        $this->assertInstanceOf(get_class($this->_object), $this->_object->setFormatter(new \Mergy\TextUI\Printer\Formatter\Text()));
        $this->assertInstanceOf(get_class($this->_object), $this->_object->setRevisions($aRevisions));
    }

    /**
     * Test the output
     */
    public function testGet() {
        $sReturn = $this->_object->get();
        $aLines = explode(PHP_EOL, $sReturn);
        $this->assertEquals(8, count($aLines));
        $this->assertContains('unspecified', $aLines[0]);
        $this->assertEquals(1, count(explode(',', $aLines[1])));
        $this->assertContains('123', $aLines[2]);
        $this->assertEquals(4, count(explode(',', $aLines[3])));
        $this->assertContains('234', $aLines[4]);
        $this->assertEquals(3, count(explode(',', $aLines[5])));
        $this->assertContains('456', $aLines[6]);
        $this->assertEquals(1, count(explode(',', $aLines[7])));
    }
}
