<?php

/**
 * Test class for \Mergy\TextUI\Printer\Group.
 * Generated by PHPUnit on 2012-03-23 at 23:24:12.
 */
namespace Mergy\Test\Mergy\TextUI\Printer;

class SingleTest extends \PHPUnit_Framework_TestCase {

    /**
     *
     * @var \Mergy\TextUI\Printer\Group
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $aRevisions = include 'tests/_files/Revisions.php';

        $this->_object = new \Mergy\TextUI\Printer\Single();
        $this->assertInstanceOf(get_class($this->_object), $this->_object->setFormatter(new \Mergy\TextUI\Printer\Formatter\Text()));
        $this->assertInstanceOf(get_class($this->_object), $this->_object->setRevisions($aRevisions));
    }

    /**
     * Test the output
     */
    public function testGet() {
        $sReturn = $this->_object->get();
        $aLines = explode(PHP_EOL, $sReturn);
        $this->assertEquals(9, count($aLines));
    }
}
